FROM node:8

#INSTALL LIBAIO1 & UNZIP (NEEDED FOR STRONG-ORACLE)
RUN apt-get update \
 && apt-get install -y libaio1 \
 && apt-get install -y build-essential \
 && apt-get install -y unzip \
 && apt-get install -y curl

RUN mkdir -p /opt/oracle
ADD ./instantclient-basiclite-linux.x64-18.3.0.0.0dbru.zip .
RUN unzip ./instantclient-basiclite-linux.x64-18.3.0.0.0dbru.zip -d /opt/oracle \
    && mv /opt/oracle/instantclient_18_3 /opt/oracle/instantclient 

ENV LD_LIBRARY_PATH="/opt/oracle/instantclient"
ENV OCI_HOME="/opt/oracle/instantclient"
ENV OCI_LIB_DIR="/opt/oracle/instantclient"
ENV OCI_INCLUDE_DIR="/opt/oracle/instantclient/sdk/include"
ENV OCI_VERSION=12
RUN echo '/opt/oracle/instantclient/' | tee -a /etc/ld.so.conf.d/oracle_instant_client.conf && ldconfig

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./
RUN npm i npm@latest -g && npm install express && npm install --save xml-js && npm install 
# copy all application source directories
COPY *.js ./
COPY *.json ./
COPY public/ public/
COPY routes/ routes/
COPY views/ views/
COPY bin/ bin/
# Expose the port and run it
EXPOSE 8080
CMD [ "npm", "start" ]